services:
  - type: web
    name: vmi-motul-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn vmi_api_deploy:app --host 0.0.0.0 --port $PORT
    plan: free
